name: WakaTime Stats

on:
  schedule:
    - cron: "0 0 * * *"   # runs daily
  workflow_dispatch:

jobs:
  update-readme:
    name: Update README with WakaTime
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      

      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_TIME: true
          SHOW_TOTAL: true
          SHOW_LANGUAGE: true
          SHOW_LINES_OF_CODE: true
          SHOW_PROJECTS: true
          SHOW_OS: true
          SHOW_EDITORS: true
          SHOW_COMMIT: true
